name: Publish NPM Package
on:
    workflow_dispatch:
    push:
      branches: [main]
    pull_request:
      branches: [main]

permissions:
    contents: read
    packages: write
    pull-requests: write # for leaving a comment on PR

env:
  PACKAGE_VERSION: ${{ github.ref_name == 'main' && format('1.0.{0}', github.RUN_NUMBER) || format('0.{0}.{1}', github.event.number, github.RUN_NUMBER) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      # Set package version
      - run: |
       git config --global user.email "${{ secrets.EMAIL }}"
       git config --global user.name "angelo-loria"
       npm version ${{ env.PACKAGE_VERSION }}
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
